on: push
name: Tests
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'

    - name: Get packages
      run: flutter pub get

    - name: Run tests
      run: flutter test --coverage

    - name: Upload test artifact
      uses: actions/upload-artifact@v1
      with:
        name: application
        path: .
